config/routes.rb
RansackTest::Application.routes.draw do
  resources :stuffs

end

app/models/stuff.rb
class Stuff < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/stuffs_controller.rb
class StuffsController < ApplicationController
  # GET /stuffs
  # GET /stuffs.json
  def index
    @stuffs = Stuff.search({"customer_id_cont"=>"2167"}).result

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stuffs }
    end
  end

  # GET /stuffs/1
  # GET /stuffs/1.json
  def show
    @stuff = Stuff.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stuff }
    end
  end

  # GET /stuffs/new
  # GET /stuffs/new.json
  def new
    @stuff = Stuff.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stuff }
    end
  end

  # GET /stuffs/1/edit
  def edit
    @stuff = Stuff.find(params[:id])
  end

  # POST /stuffs
  # POST /stuffs.json
  def create
    @stuff = Stuff.new(params[:stuff])

    respond_to do |format|
      if @stuff.save
        format.html { redirect_to @stuff, notice: 'Stuff was successfully created.' }
        format.json { render json: @stuff, status: :created, location: @stuff }
      else
        format.html { render action: "new" }
        format.json { render json: @stuff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stuffs/1
  # PUT /stuffs/1.json
  def update
    @stuff = Stuff.find(params[:id])

    respond_to do |format|
      if @stuff.update_attributes(params[:stuff])
        format.html { redirect_to @stuff, notice: 'Stuff was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stuff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stuffs/1
  # DELETE /stuffs/1.json
  def destroy
    @stuff = Stuff.find(params[:id])
    @stuff.destroy

    respond_to do |format|
      format.html { redirect_to stuffs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stuffs_helper.rb
module StuffsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RansackTest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stuffs/_form.html.erb
<%= form_for(@stuff) do |f| %>
  <% if @stuff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stuff.errors.count, "error") %> prohibited this stuff from being saved:</h2>

      <ul>
      <% @stuff.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stuffs/edit.html.erb
<h1>Editing stuff</h1>

<%= render 'form' %>

<%= link_to 'Show', @stuff %> |
<%= link_to 'Back', stuffs_path %>

app/views/stuffs/index.html.erb
<h1>Listing stuffs</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stuffs.each do |stuff| %>
  <tr>
    <td><%= link_to 'Show', stuff %></td>
    <td><%= link_to 'Edit', edit_stuff_path(stuff) %></td>
    <td><%= link_to 'Destroy', stuff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stuff', new_stuff_path %>

app/views/stuffs/new.html.erb
<h1>New stuff</h1>

<%= render 'form' %>

<%= link_to 'Back', stuffs_path %>

app/views/stuffs/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_stuff_path(@stuff) %> |
<%= link_to 'Back', stuffs_path %>